language: ruby

sudo: false

# cache:
#   bundler: true
#   directories:
#     - reports
#     - vendor/cache

# rvm:
#   - 2.3.1
#   - ruby-head

addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch

services:
  - elasticsearch

install: true


# bundler_args: --jobs=3 --retry=3 --without development

# git:
#   submodules: true

# before_install:
#   - git submodule update --init
#   - sh -c "if [ '$RUBYGEMS_VERSION' != 'latest' ]; then gem update --system $RUBYGEMS_VERSION; fi"
#   - gem --version
#   - script/install_toxiproxy.sh

# before_script:
#   - cp config/database.yml.example config/database.yml
#   - bundle exec rake db:create db:migrate db:test:prepare

script:
  - elasticsearch -v
  - curl http://localhost:9200/
#   - bundle exec rake
#   - bundle exec rake rubocop
#   - script/brakeman
#   - bundle exec cap -T > /dev/null

# env:
#   - RUBYGEMS_VERSION=2.6.4
#   - RUBYGEMS_VERSION=latest

# matrix:
#   allow_failures:
#     - env: "RUBYGEMS_VERSION=latest"
#     - rvm: ruby-head
#   fast_finish: true
